import type { Metadata } from "next";

import { PhasePlaceholder } from "@/components/layout/phase-placeholder";

/**
 * Turns a slug into something presentable without a content file to read.
 *
 * Known initialisms stay uppercase; anything else gets title-cased. Phase 7 replaces this
 * entirely with the `title` from the page's front matter — this exists only so the heading and
 * the tab title are not a raw slug in the meantime.
 */
const INITIALISMS = new Set(["tsh", "hba1c", "ldl", "hdl", "cbc", "alt", "ast", "crp", "psa", "t3", "t4"]);

function titleFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((part) =>
      INITIALISMS.has(part.toLowerCase())
        ? part.toUpperCase()
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join(" ");
}

export async function generateMetadata({
  params,
}: PageProps<"/biomarkers/[slug]">): Promise<Metadata> {
  const { slug } = await params;
  const title = titleFromSlug(slug);

  return {
    title,
    description: `What ${title} measures, why it is tested, and how to read your result against the reference range on your report.`,
    openGraph: {
      title: `${title} — Medi-Scan`,
      description: `A plain-language explanation of ${title}.`,
      type: "article",
    },
  };
}

export default async function BiomarkerPage({ params }: PageProps<"/biomarkers/[slug]">) {
  const { slug } = await params;
  const title = titleFromSlug(slug);

  return (
    <PhasePlaceholder heading={title} phase="phase 7">
      <p>
        This page will render the curated reference content for {title} from markdown, as a
        statically generated page with OpenGraph metadata and JSON&#8209;LD structured data.
      </p>
      <p>
        It is deliberately not generated by a model. The same text is what chat answers are
        grounded in, so it is written and reviewed by hand against cited sources — a page that
        was itself AI-written would make &ldquo;grounded in reviewed content&rdquo; meaningless.
      </p>
      <p>
        Markdown rendering is not wired up yet: it needs a renderer with raw HTML disabled, and
        that dependency belongs to the phase that uses it rather than being added early.
      </p>
    </PhasePlaceholder>
  );
}
